M48
; DRILL file {KiCad (7.0.0)} date Mon Aug  7 02:07:43 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-07T02:07:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X0.15Y0.7746
X0.3776Y0.7746
T2
X-0.7874Y0.9055
X0.0Y0.1181
X0.7874Y-1.063
T0
M30
